# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7aae78f757522d30469742c339ebe6f5e7839dbb6290863db72faf0fc0105b1862dc9787ca38ccaa1aa5f0d6be8a1cd7fb48f1e6d05b37afbabda9fbcbb42099

test:
  secret_key_base: a3f66bbe47740797793be3bb2101c1118c5d2e097b0fac0c747c5d1f8ee39675b6fe18ee16ff43ddd9906d194c5e4ce388d52b8dea28e61bba33c861ae57cb49

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
